version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    container_name: hr_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passsword
      POSTGRES_DB: hr_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
